version: '3.9'

services:
  chatbot-service:
    build: .
    container_name: chatbot-service
    working_dir: /app/src
    command: python chatbot.py
    ports:
      - "8033:8001"  # Expose port for chatbot service
    volumes:
      - ./src:/app/chatbot  # Map local code to container
    depends_on:
      - login-service
      - main-service

  login-service:
    build: .
    container_name: login-service
    working_dir: /app/src
    command: python login.py
    ports:
      - "5001:8002"  # Expose port for login service
    volumes:
      - ./src:/app/login  # Map local code to container

  main-service:
    build: .
    container_name: main-service
    working_dir: /app/src
    command: python main.py
    ports:
      - "5004:8003"  # Expose port for main service
    volumes:
      - ./src:/app/main  # Map local code to container
